apps/comment/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import AddcommentView, NotificationView, mark_to_read, mark_to_delete

urlpatterns = [
    path('add/', AddcommentView, name='add_comment'),
    path('notification/', NotificationView, name='notification'),
    path('notification/no-read/', NotificationView, {'is_read': 'false'}, name='notification_no_read'),
    path('notification/mark-to-read/', mark_to_read, name='mark_to_read'),
    path('notification/mark-to-delete/', mark_to_delete, name='mark_to_delete'),
]

izone/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from blog.feeds import AllArticleRssFeed
from blog.views import robots

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/blog/img/favicon.ico')),
    path('adminx/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  # allauth
    path('accounts/', include(('oauth.urls', 'oauth'), namespace='oauth')),  # oauth,只展现一个用户登录界面
    path('', include(('blog.urls', 'blog'), namespace='blog')),  # blog
    path('comment/',include(('comment.urls', 'comment'),namespace='comment')), # comment
    path('robots.txt', robots, name='robots'), # robots
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'), # 网站地图
    path('feed/', AllArticleRssFeed(), name='rss'),   # rss订阅
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

if settings.API_FLAG:
    from api.urls import router
    urlpatterns.append(path('api/v1/',include((router.urls, router.root_view_name),namespace='api')))    # restframework

if settings.TOOL_FLAG:
    urlpatterns.append(path('tool/', include(('tool.urls', 'tool'),namespace='tool')))    # tool

apps/comment/models.py
from django.db import models
from django.conf import settings
from blog.models import Article
import re

import markdown

emoji_info = [
    [('aini_org', '爱你'), ('baibai_thumb', '拜拜'),
     ('baobao_thumb', '抱抱'), ('beishang_org', '悲伤'),
     ('bingbujiandan_thumb', '并不简单'), ('bishi_org', '鄙视'),
     ('bizui_org', '闭嘴'), ('chanzui_org', '馋嘴')],
    [('chigua_thumb', '吃瓜'), ('chongjing_org', '憧憬'),
     ('dahaqian_org', '哈欠'), ('dalian_org', '打脸'),
     ('ding_org', '顶'), ('doge02_org', 'doge'),
     ('erha_org', '二哈'), ('gui_org', '跪了')],
    [('guzhang_thumb', '鼓掌'), ('haha_thumb', '哈哈'),
     ('heng_thumb', '哼'), ('huaixiao_org', '坏笑'),
     ('huaxin_org', '色'), ('jiyan_org', '挤眼'),
     ('kelian_org', '可怜'), ('kuxiao_org', '允悲')],
    [('ku_org', '酷'), ('leimu_org', '泪'),
     ('miaomiao_thumb', '喵喵'), ('ningwen_org', '疑问'),
     ('nu_thumb', '怒'), ('qian_thumb', '钱'),
     ('sikao_org', '思考'), ('taikaixin_org', '太开心')],
    [('tanshou_org', '摊手'), ('tianping_thumb', '舔屏'),
     ('touxiao_org', '偷笑'), ('tu_org', '吐'),
     ('wabi_thumb', '挖鼻'), ('weiqu_thumb', '委屈'),
     ('wenhao_thumb', '费解'), ('wosuanle_thumb', '酸')],
    [('wu_thumb', '污'), ('xiaoerbuyu_org', '笑而不语'),
     ('xiaoku_thumb', '笑cry'), ('xixi_thumb', '嘻嘻'),
     ('yinxian_org', '阴险'), ('yun_thumb', '晕'),
     ('zhouma_thumb', '怒骂'), ('zhuakuang_org', '抓狂')]
]


def get_emoji_imgs(body):
    '''
    替换掉评论中的标题表情，并且把表情替换成图片地址
    :param body:
    :return:
    '''
    img_url = '<img class="comment-emoji-img" src="/static/comment/weibo/{}.png" title="{}" alt="{}">'
    for i in emoji_info:
        for ii in i:
            emoji_url = img_url.format(ii[0], ii[1], ii[0])
            body = re.sub(':{}:'.format(ii[0]), emoji_url, body)
    tag_info = {
        '<h\d>': '',
        '</h\d>': '<br>'
    }
    for k, v in tag_info.items():
        body = re.sub(k, v, body)
    return body


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='%(class)s_related',
                               verbose_name='评论人', on_delete=models.CASCADE)
    create_date = models.DateTimeField('创建时间', auto_now_add=True)
    content = models.TextField('评论内容')
    parent = models.ForeignKey('self', verbose_name='父评论', related_name='%(class)s_child_comments', blank=True,
                               null=True, on_delete=models.CASCADE)
    rep_to = models.ForeignKey('self', verbose_name='回复', related_name='%(class)s_rep_comments',
                               blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        '''这是一个元类，用来继承的'''
        abstract = True

    def __str__(self):
        return self.content[:20]

    def content_to_markdown(self):
        to_md = markdown.markdown(self.content,
                                  safe_mode='escape',
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                  ])
        return get_emoji_imgs(to_md)


class ArticleComment(Comment):
    belong = models.ForeignKey(Article, related_name='article_comments', verbose_name='所属文章',
                               on_delete=models.CASCADE)

    class Meta:
        verbose_name = '文章评论'
        verbose_name_plural = verbose_name
        ordering = ['create_date']


class Notification(models.Model):
    create_p = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='提示创建者', related_name='notification_create',
                                 on_delete=models.CASCADE)
    get_p = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='提示接收者', related_name='notification_get',
                              on_delete=models.CASCADE)
    comment = models.ForeignKey(ArticleComment, verbose_name='所属评论', related_name='the_comment',
                                on_delete=models.CASCADE)
    create_date = models.DateTimeField('提示时间', auto_now_add=True)
    is_read = models.BooleanField('是否已读', default=False)

    def mark_to_read(self):
        self.is_read = True
        self.save(update_fields=['is_read'])

    class Meta:
        verbose_name = '提示信息'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return '{}@了{}'.format(self.create_p, self.get_p)

apps/comment/views.py
from django.shortcuts import render
from blog.models import Article
from .models import ArticleComment, Notification
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.shortcuts import get_object_or_404
from . import handlers

user_model = settings.AUTH_USER_MODEL


@login_required
@require_POST
def AddcommentView(request):
    if request.is_ajax() and request.method == "POST":
        data = request.POST
        new_user = request.user
        new_content = data.get('content')
        article_id = data.get('article_id')
        rep_id = data.get('rep_id')
        the_article = Article.objects.get(id=article_id)
        if len(new_content) > 1048:
            return JsonResponse({'msg': '你的评论字数超过1048，无法保存。'})

        if not rep_id:
            new_comment = ArticleComment(author=new_user, content=new_content, belong=the_article, parent=None,
                                         rep_to=None)
        else:
            new_rep_to = ArticleComment.objects.get(id=rep_id)
            new_parent = new_rep_to.parent if new_rep_to.parent else new_rep_to
            new_comment = ArticleComment(author=new_user, content=new_content, belong=the_article, parent=new_parent,
                                         rep_to=new_rep_to)
        new_comment.save()
        new_point = '#com-' + str(new_comment.id)
        return JsonResponse({'msg': '评论提交成功！', 'new_point': new_point})
    return JsonResponse({'msg': '评论失败！'})


@login_required
def NotificationView(request, is_read=None):
    '''展示提示消息列表'''
    now_date = datetime.now()
    return render(request, 'comment/notification.html', context={'is_read': is_read, 'now_date': now_date})


@login_required
@require_POST
def mark_to_read(request):
    '''将一个消息标记为已读'''
    if request.is_ajax() and request.method == "POST":
        data = request.POST
        user = request.user
        id = data.get('id')
        info = get_object_or_404(Notification, get_p=user, id=id)
        info.mark_to_read()
        return JsonResponse({'msg': 'mark success'})
    return JsonResponse({'msg': 'miss'})


@login_required
@require_POST
def mark_to_delete(request):
    '''将一个消息删除'''
    if request.is_ajax() and request.method == "POST":
        data = request.POST
        user = request.user
        id = data.get('id')
        info = get_object_or_404(Notification, get_p=user, id=id)
        info.delete()
        return JsonResponse({'msg': 'delete success'})
    return JsonResponse({'msg': 'miss'})

apps/comment/templates/comment/comment_form.html
{% load static comment_tags %}
<div class="card border-0 rounded-0 f-16" id="editor-block">
    {% if user.is_authenticated %}
    <div class="card-body p-2 p-md-3">
        <textarea class="form-control rounded-0" id="comment-form" name="text"
                  placeholder="评论请使用 markdown 语法" rows="5" required></textarea>
    </div>
    <div class="card-footer border-0 bg-white py-0 px-2 px-md-3" id="editor-footer">
        <button type="button" class="btn btn-info btn-sm float-right f-16"
                id="push-com" data-csrf="{{ csrf_token }}" data-article-id="{{ article.id }}"
                data-ajax-url="{% url 'comment:add_comment' %}">提交评论</button>
        <button class="btn btn-sm py-0 px-2" id="emoji-btns" type="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-smile-o fa-2x"></i>
        </button>
        <div class="dropdown-menu" id='emoji-list' aria-labelledby="emoji-btns">
            {% get_emoji_imgs as emoji_imgs %}
            {% for emoji_list in emoji_imgs %}
            <div class="editor-btns px-2">
                {% for emoji in emoji_list %}
                {% with emoji.0|emoji_to_url as emoji_url %}
                <button class="btn p-1"><img
                        src="{% static emoji_url %}"
                        title="{{ emoji.1 }}" alt="{{ emoji.0 }}"
                        data-emoji=":{{ emoji.0 }}:"></button>
                {% endwith %}
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
    <div class="card-body text-center m-2 m-md-3 f-16" id="no-editor">
        <div>您尚未登录，请
            <a class="text-danger" href="{% url 'account_login' %}?next={{ request.path }}">登录</a> 或
            <a class="text-danger" href="{% url 'account_signup' %}?next={{ request.path }}">注册</a> 后评论
        </div>
        <div class="login-link mt-2">
            <a class="mx-3" href="/accounts/weibo/login/?next={{ request.path }}" title="社交账号登录有点慢，请耐心等候！"><i
                    class="fa fa-weibo fa-2x"></i></a>
            <a class="mx-3" href="/accounts/github/login/?next={{ request.path }}" title="社交账号登录有点慢，请耐心等候！"><i
                    class="fa fa-github fa-2x"></i></a>
        </div>
    </div>
    {% endif %}
</div>

apps/comment/templates/comment/comment_list.html
{% load comment_tags oauth_tags %}
{% load humanize %}

<div class="card-body p-2 p-md-3 f-17" id="comment-list">
    <ul class="list-unstyled">
        <div class="mb-3">
            <strong>{% get_comment_user_count article %}&nbsp;人参与&nbsp;|&nbsp;{% get_comment_count article %}&nbsp;条评论</strong>
        </div>
        {% for comment in comment_list %}
        <div class="comment-parent pt-2" id="com-{{ comment.id }}">
            <li class="media">
                {% get_user_avatar_tag comment.author %}
                <div class="media-body ml-2">
                    <a class="float-right small mr-2 rep-btn" href="#editor-block"
                       data-repid="{{ comment.id }}" data-repuser="{{ comment.author.username }}">回复</a>
                    <p class="mt-0 mb-1">
                        {% get_user_link comment.author as user_link_info %}
                        {% if user_link_info.is_verified and user_link_info.link %}
                        <strong >
                            <a href="{{ user_link_info.link }}"
                               title="前往 {{ comment.author }} 的个人网站"
                               target="_blank">{{ comment.author }}
                            </a>
                        </strong>
                        {% else %}
                        <strong title="该用户未认证或没有个人站点">{{ comment.author }}</strong>
                        {% endif %}
                        {% if user_link_info.is_verified %}
                            {% if user_link_info.provider == 'GitHub' %}
                            <i class="fa fa-github" title="Github 绑定用户"></i>
                            {% elif user_link_info.provider == 'Weibo' %}
                            <i class="fa fa-weibo" title="Weibo 绑定用户"></i>
                            {% else %}
                            <i class="fa fa-envelope-o" title="邮箱认证用户"></i>
                            {% endif %}
                        {% endif %}
                        {% if comment.author.is_superuser %}
                        <small class="text-danger">[博主]</small>
                        {% endif %}
                    </p>
                    <p class="small text-muted">{{ forloop.revcounter }}&nbsp;楼&nbsp;-&nbsp;{{ comment.create_date|naturaltime }}</p>
                </div>
            </li>
            <div class="comment-body">{{ comment.content_to_markdown|safe }}</div>
        </div>
        {% get_child_comments comment as child_comments %}
        {% if child_comments %}
        <ul class="list-unstyled ml-4">
            {% for each in child_comments %}
            <div class="comment-child pt-2" id="com-{{ each.id }}">
                <li class="media">
                    {% get_user_avatar_tag each.author %}
                    <div class="media-body ml-2">
                        <a class="float-right small mr-2 rep-btn" href="#editor-block"
                           data-repid="{{ each.id }}" data-repuser="{{ each.author.username }}">回复</a>
                        <p class="mt-0 mb-1">
                            {% get_user_link each.author as each_user_link_info %}
                            {% if each_user_link_info.is_verified and each_user_link_info.link %}
                            <strong >
                                <a href="{{ each_user_link_info.link }}"
                                   title="前往 {{ each.author }} 的个人网站"
                                   target="_blank">{{ each.author }}
                                </a>
                            </strong>
                            {% else %}
                            <strong title="该用户未认证或没有个人站点">{{ each.author }}</strong>
                            {% endif %}
                            {% if each_user_link_info.is_verified %}
                                {% if each_user_link_info.provider == 'GitHub' %}
                                <i class="fa fa-github" title="Github 绑定用户"></i>
                                {% elif each_user_link_info.provider == 'Weibo' %}
                                <i class="fa fa-weibo" title="Weibo 绑定用户"></i>
                                {% else %}
                                <i class="fa fa-envelope-o" title="邮箱认证用户"></i>
                                {% endif %}
                            {% endif %}
                            {% if each.author.is_superuser %}
                            <small class="text-danger">[博主]</small>
                            {% endif %}
                            <i class="fa fa-share"></i>
                            @{{ each.rep_to.author.username }}
                        </p>
                        <p class="small text-muted">{{ each.create_date|naturaltime }}</p>
                    </div>
                </li>
                <div class="comment-body">{{ each.content_to_markdown|safe }}</div>
            </div>
            {% endfor %}
        </ul>
        {% endif %}
        {% empty %}
        暂时没有评论，欢迎来尬聊！
        {% endfor %}
    </ul>
</div>

apps/comment/templates/comment/notification.html
{% extends 'blog/base.html' %}
{% load static %}
{% load humanize %}
{% load comment_tags %}

{% block head_title %}个人信息推送{% endblock %}

{% block top-file %}
<link href="{% static 'comment/css/notification.css' %}?v=20190704" rel="stylesheet">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-lg-9">
            {% get_notifications user is_read as notifications %}
            <ul class="cbp_tmtimeline f-16">
                {% for each in notifications %}
                <li>
                    <time class="cbp_tmtime" datetime="{{ each.create_date }}">
                        <span>{{ each.create_date|date:"Y/m/d"}}</span>
                        <span>{{ each.create_date|date:"H:i"}}</span>
                    </time>
                    <div class="cbp_tmicon"><i class="fa fa-envelope"></i></div>
                    <div class="cbp_tmlabel">
                        <h2>
                            <strong>{{ each.create_p }}</strong>&nbsp;在&nbsp;
                            <a class="text-info" title="查看评论详情"
                               href="{{ each.comment.belong.get_absolute_url }}#com-{{ each.comment.id }}">
                                {{ each.comment.belong.title }}</a>&nbsp;中@了你，并评论道：
                        </h2>
                        <p>{{ each.comment.content|truncatechars:130 }}</p>
                        {% if not each.is_read %}
                        <div class="to_read pb-1">
                            <button class="btn btn-success float-right rounded-0 f-16" data-id="{{ each.id }}"
                                    data-csrf="{{ csrf_token }}" data-url="{% url 'comment:mark_to_read' %}">标为已读
                            </button>
                        </div>
                        {% else %}
                        <div class="to_delete pb-1">
                            <button class="btn btn-danger float-right rounded-0 f-16" data-id="{{ each.id }}"
                                    data-csrf="{{ csrf_token }}" data-url="{% url 'comment:mark_to_delete' %}">删除信息
                            </button>
                        </div>
                        {% endif %}
                    </div>
                </li>
                {% empty %}
                <li>
                    <time class="cbp_tmtime" datetime="{{ now_date }}">
                        <span>{{ now_date|date:"Y/m/d"}}</span>
                        <span>{{ now_date|date:"H:i"}}</span>
                    </time>
                    <div class="cbp_tmicon"><i class="fa fa-envelope"></i></div>
                    <div class="cbp_tmlabel">
                        <h2>你暂时没有任何推送消息！</h2>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-4 col-lg-3">
            <div class="card rounded-0 border-0" id="notes-main">
                <div class="card-header bg-white border-0">
                    <h4><strong><i class="fa fa-bell-o mr-1"></i>&nbsp;提示信息</strong></h4>
                </div>
                <div class="card-body pt-0 url-menu">
                    <ul class="list-group">
                        {% url 'comment:notification' as all_url %}
                        {% url 'comment:notification_no_read' as no_read_url %}
                        <a class="list-group-item rounded-0 {% if request.path == all_url %}active{% endif %}"
                           href="{{ all_url }}">全部信息
                            <span class="badge float-right">{% get_notifications_count user %}</span>
                        </a>
                        <a class="list-group-item rounded-0 {% if request.path == no_read_url %}active{% endif %}"
                           href="{{ no_read_url }}">未读信息
                            <span class="badge float-right">{% get_notifications_count user 'false' %}</span>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block end_file %}
<script src="{% static 'comment/js/notification.js' %}?v=23"></script>
{% endblock %}